// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TracNghiem.Data;

#nullable disable

namespace TracNghiem.Migrations
{
    [DbContext(typeof(TracNghiemContext))]
    partial class TracNghiemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TracNghiem.Models.CauHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CauHoi1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAnA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAnB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAnC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapAnD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaMonHoc")
                        .HasColumnType("int");

                    b.Property<int?>("MaMonHocNavigationId")
                        .HasColumnType("int");

                    b.Property<int?>("MaMucDo")
                        .HasColumnType("int");

                    b.Property<int?>("MaMucDoNavigationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaMonHocNavigationId");

                    b.HasIndex("MaMucDoNavigationId");

                    b.ToTable("CauHoi");
                });

            modelBuilder.Entity("TracNghiem.Models.DeThi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("NgayThi")
                        .HasColumnType("date");

                    b.Property<int?>("SoLuongCauHoi")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongCauKho")
                        .HasColumnType("int");

                    b.Property<string>("TenDeThi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThoiGianThi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DeThi");
                });

            modelBuilder.Entity("TracNghiem.Models.DeThiCauHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaCauHoi")
                        .HasColumnType("int");

                    b.Property<int?>("MaCauHoiNavigationId")
                        .HasColumnType("int");

                    b.Property<int?>("MaDeThi")
                        .HasColumnType("int");

                    b.Property<int?>("MaDeThiNavigationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaCauHoiNavigationId");

                    b.HasIndex("MaDeThiNavigationId");

                    b.ToTable("DeThiCauHoi");
                });

            modelBuilder.Entity("TracNghiem.Models.KetQua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DapAn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaDeThiCauHoi")
                        .HasColumnType("int");

                    b.Property<int?>("MaDeThiCauHoiNavigationId")
                        .HasColumnType("int");

                    b.Property<string>("MaSinhVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSinhVienNavigationId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MaDeThiCauHoiNavigationId");

                    b.HasIndex("MaSinhVienNavigationId");

                    b.ToTable("KetQua");
                });

            modelBuilder.Entity("TracNghiem.Models.MonHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenMonHoc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("TracNghiem.Models.MucDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenMucDo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MucDo");
                });

            modelBuilder.Entity("TracNghiem.Models.ThanhVien", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Email")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte?>("GioiTinh")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("LaGiangVien")
                        .HasColumnType("tinyint");

                    b.Property<string>("Lop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSinhVien")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ThanhVien");
                });

            modelBuilder.Entity("TracNghiem.Models.CauHoi", b =>
                {
                    b.HasOne("TracNghiem.Models.MonHoc", "MaMonHocNavigation")
                        .WithMany("CauHois")
                        .HasForeignKey("MaMonHocNavigationId");

                    b.HasOne("TracNghiem.Models.MucDo", "MaMucDoNavigation")
                        .WithMany("CauHois")
                        .HasForeignKey("MaMucDoNavigationId");

                    b.Navigation("MaMonHocNavigation");

                    b.Navigation("MaMucDoNavigation");
                });

            modelBuilder.Entity("TracNghiem.Models.DeThiCauHoi", b =>
                {
                    b.HasOne("TracNghiem.Models.CauHoi", "MaCauHoiNavigation")
                        .WithMany("DeThiCauHois")
                        .HasForeignKey("MaCauHoiNavigationId");

                    b.HasOne("TracNghiem.Models.DeThi", "MaDeThiNavigation")
                        .WithMany("DeThiCauHois")
                        .HasForeignKey("MaDeThiNavigationId");

                    b.Navigation("MaCauHoiNavigation");

                    b.Navigation("MaDeThiNavigation");
                });

            modelBuilder.Entity("TracNghiem.Models.KetQua", b =>
                {
                    b.HasOne("TracNghiem.Models.DeThiCauHoi", "MaDeThiCauHoiNavigation")
                        .WithMany("KetQuas")
                        .HasForeignKey("MaDeThiCauHoiNavigationId");

                    b.HasOne("TracNghiem.Models.ThanhVien", "MaSinhVienNavigation")
                        .WithMany("KetQuas")
                        .HasForeignKey("MaSinhVienNavigationId");

                    b.Navigation("MaDeThiCauHoiNavigation");

                    b.Navigation("MaSinhVienNavigation");
                });

            modelBuilder.Entity("TracNghiem.Models.CauHoi", b =>
                {
                    b.Navigation("DeThiCauHois");
                });

            modelBuilder.Entity("TracNghiem.Models.DeThi", b =>
                {
                    b.Navigation("DeThiCauHois");
                });

            modelBuilder.Entity("TracNghiem.Models.DeThiCauHoi", b =>
                {
                    b.Navigation("KetQuas");
                });

            modelBuilder.Entity("TracNghiem.Models.MonHoc", b =>
                {
                    b.Navigation("CauHois");
                });

            modelBuilder.Entity("TracNghiem.Models.MucDo", b =>
                {
                    b.Navigation("CauHois");
                });

            modelBuilder.Entity("TracNghiem.Models.ThanhVien", b =>
                {
                    b.Navigation("KetQuas");
                });
#pragma warning restore 612, 618
        }
    }
}
